### ISSUE TITLE
TODO list for v1

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/tdbm-graphql#1]
- [x] one-to-many relationships
- [x] many-to-many relationships
- [ ] support for inheritance
- [x] support for conditions / rights

Note: v1 will only contain queries, no updates

**Comment by moufmouf** [comment]
Support for inheritance was added in v3!
Closing.
